# Generated by Django 3.1.6 on 2021-02-11 18:48

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rsaDemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='createsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='messageModel',
            fields=[
                ('messageId', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('bits', models.IntegerField(choices=[(128, '128 bits'), (256, '256 bits'), (512, '512 bits'), (1024, '1024 bits'), (2048, '2048 bits')], default='128')),
                ('cipherText', models.TextField(blank=True, null=True)),
                ('sender', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('read', models.BooleanField(default=False)),
                ('ctlist', models.TextField(blank=True, null=True)),
                ('publicKey', models.TextField(blank=True, null=True)),
                ('phi', models.TextField(blank=True, null=True)),
                ('modulus', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='roomHasMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsaDemo.messagemodel')),
            ],
        ),
        migrations.CreateModel(
            name='roomModel',
            fields=[
                ('roomId', models.BigAutoField(primary_key=True, serialize=False)),
                ('roomName', models.CharField(max_length=200, unique=True)),
                ('roomType', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=50)),
                ('createdOn', models.DateTimeField(default=datetime.datetime.now)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='auth.user')),
                ('uid', models.BigAutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userModel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='rsaModel',
        ),
        migrations.AddField(
            model_name='roomhasmessages',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsaDemo.roommodel'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rsaDemo.roommodel'),
        ),
        migrations.AddField(
            model_name='createsmodel',
            name='roomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsaDemo.roommodel'),
        ),
        migrations.AddField(
            model_name='createsmodel',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsaDemo.usermodel'),
        ),
    ]
