# Generated by Django 3.1.6 on 2021-02-11 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('rsaDemo', '0002_auto_20210211_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createsmodel',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='userModel',
        ),
    ]
